### ISSUE TITLE
Changing Rooms Freezes/Breaks Game

### ISSUE THREAD

**Issue by zachllogan** [random-person-001/MagicText#20] opened 2016-10-20 03:34 UTC
when I go into BanditFortress and then back to Cliffside the game freezes. Also freezes if I enter SoursePit in ghost mode (I can't enter it in normal.) I'm still getting familiar with version control so maybe I caused this locally?(though I did try after running a revert, so I don't think so?) Do you guys get this problem?

**Comment by HazilTheNut** [comment] 2016-10-20 14:03
You should try to update the projrct under 'VCS'. You can also go to local
changes and revert local changes to reset to current branch code. Room
switching seems to work for everyone else.

**Comment by random-person-001** [comment] 2016-10-20 16:02
A note: we've been committing to the multiplayer branch ([visualization](https://github.com/random-person-001/MagicText/network)) a lot recently, you could try switching there to see if the problem is resolved there.
Also, you could see whether it's the room border being weird or the entire room switching system being weird by cheating yourself there: activate the HUD command line (by ▓▓▓▓▓▓▓ ▓ ▓▓▓▓▓▓) and then type `jumpto SourcePit`  If that works and walking over there didn't, we have a more annoying problem to fix :cry:  But at least it'll narrow down where the problem is.

**_(sensitive info redacted)_**

**Comment by zachllogan** [comment] 2016-10-20 21:35
I tried the multiplayer one and it works fine, but the master is broken for me; is it broken for you? The problem happens both when using jumpto and when walking. Also I don't exactly understand how the github thing works because last night I committed to master, but that hasn't shown up in the commit section and when I just redownloaded the master it didn't have any changes to it. So what exactly is a commit and what exactly is a pull. Also should I do #7 on the multiplayer as well? Are both still being worked on or is multiplayer soon going t replace master?

**Comment by random-person-001** [comment] 2016-10-21 01:49
Well, the multiplayer branch will eventually be merged into master once most things are worked out with it.  The point of having different branches is that people can be developing different functionalities at the same time and work out the kinks in a feature before it's put into the official, stabler branch of the code.  (so if we were doing this perfectly, commits like making water prettier should go in the main branch, while people like me commit multiplayer related changes to the multiplayer branch, to be merged when no longer buggy).  Because it works that way, it'd be weird if you made your change to both branches.

Committing is just saving your code changes, so that you are able to go back to a specific time if something breaks.  Usually you write a commit message with each commit, giving a short description of what you changed (or why, or how, or whatever.  Nobody's grading us on this 😆, just don't do [this](http://imgs.xkcd.com/comics/git_commit.png)).  In this case, you probably committed your changes, but didn't see the option "commit and [push](http://gitref.org/remotes/#push)"\* as dropdown from the blue 'commit' button in the respective popup:
![commit and push dialoge](http://i.stack.imgur.com/aVvn6.png)

As for whether the room switching in the master branch is broken, well, I wouldn't be surprised if it that was the case.  (I currently don't have my computer in front of me and will be somewhere else till monday 😢 )

*that source tells a little about pushing.  You don't have to follow the actual instructions, as we can do everything through the IntelliJ GUI rather than command line, meaning it's a little harder to mess things up.  Now that you've probably made a commit to your local VC, there's probably a button somewhere in the menus to 'push' or 'push upstream' or 'push to remote' or something.  Press that to make the changes known by github, so that everyone can see it online and stuff.  Anyhow, [this diagram](http://krishnaiitd.github.io/gitcommands/images/GitWorkflow-3.png) shows some git operations visually.  For our purposes, we only care about the 'workspace' and 'remote', which is why it's convenient to press the 'commit and push' button.  If you felt ambitious you could look up more on the theory of version control or intro to using git, but on the other hand I'm fine just answering your questions as they come up 😃

**Comment by random-person-001** [comment] 2016-11-02 01:29
Probably fixed by 1ee429de8a2c4151612704377374246b4881f373

We can reopen the issue if not.

**Closed as completed by random-person-001** 2016-11-02 01:29 UTC
Labels: bug
